import {supabase} from "./lib/supabase.js";
import {requireAuth} from "./lib/guard.js";
import {uploadPublicMany,publicUrlToPath,deletePublicFiles} from "./lib/media.js";
import {escapeHTML} from "./lib/security.js";
import {loading,toast} from "./lib/ui.js";
import {money,param} from "./lib/format.js";

const type=param("type")||"marketplace", id=param("id");
const table={marketplace:"listings",housing:"housing",academic:"academic_resources",printing:"printing_providers",service:"skill_services"}[type]||"listings";
const ownerField={marketplace:"posted_by",housing:"posted_by",academic:"uploaded_by",printing:"owner_id",service:"provider_id"}[type];
const label={marketplace:"Marketplace",housing:"Accommodation",academic:"Academic resource",printing:"Printing station",service:"Student service"}[type]||"Listing";
const back={marketplace:"marketplace.html",housing:"accommodation.html",academic:"academics.html",printing:"printing.html",service:"services.html"}[type]||"home.html";
const form=document.querySelector("#editForm"),fields=document.querySelector("#editFields"),preview=document.querySelector("#editPreview"),counter=document.querySelector("#editCounter"),button=document.querySelector("#editButton");
let record=null, existing=[], added=[];
const input=(n,l,v="",req=false,t="text")=>`<div class="field"><label for="${n}">${l}</label><input id="${n}" name="${n}" type="${t}" value="${escapeHTML(v??"")}" ${req?"required":""}></div>`;
const area=(n,l,v="")=>`<div class="field"><label for="${n}">${l}</label><textarea id="${n}" name="${n}" rows="5">${escapeHTML(v??"")}</textarea></div>`;
const select=(n,l,v,opts)=>`<div class="field"><label for="${n}">${l}</label><select id="${n}" name="${n}">${opts.map(x=>`<option ${x===v?"selected":""}>${escapeHTML(x)}</option>`).join("")}</select></div>`;
function build(x){
 if(type==="marketplace")return input("title","Item title",x.title,true)+select("category","Category",x.category||"Other",["Academic","Electronics","Clothing","Furniture","Food","Other"])+input("price","Price (MWK)",x.price??"",false,"number")+input("contact_number","WhatsApp number",x.contact_number,true,"tel")+select("item_condition","Condition",x.item_condition||"Used / Fair Condition",["Brand New","Like New","Slightly Used","Used / Fair Condition"])+input("location_details","Location",x.location_details||"")+area("description","Description",x.description||"");
 if(type==="housing")return input("title","Accommodation name",x.title,true)+input("location_details","Location",x.location_details,true)+input("rent","Monthly rent (MWK)",x.rent??"",false,"number")+input("contact_number","Contact / WhatsApp",x.contact_number,true,"tel")+input("utilities","Utilities",x.utilities||"")+input("security_notes","Security",x.security_notes||"")+area("description","Description",x.description||"");
 if(type==="printing")return input("name","Station name",x.name,true)+input("location_details","Location",x.location_details||"")+input("contact_number","WhatsApp number",x.contact_number,true,"tel")+select("available","Availability",x.available?"true":"false",["true","false"])+area("notes","Station details",x.notes||"");
 if(type==="academic")return input("title","Resource title",x.title,true)+select("department","Department",x.department||"Sciences",["Sciences","Humanities","Social Sciences","Languages & Communication"])+input("academic_year","Academic year",x.academic_year||"")+input("course_code","Course code",x.course_code||"")+`<div class="field"><label for="resourceFile">Replace document (optional)</label><input id="resourceFile" name="resourceFile" type="file" accept=".pdf,.doc,.docx"><small class="muted">Leave empty to keep the current document: ${escapeHTML(x.file_name||"current document")}</small></div>`;
 return input("provider_name","Your name",x.provider_name,true)+input("service_title","Service title",x.service_title,true)+input("skill_category","Category",x.skill_category,true)+input("contact_number","WhatsApp number",x.contact_number,true,"tel")+input("starting_price","Starting price (MWK)",x.starting_price??"",false,"number")+area("description","Description",x.description||"");
}
function renderPhotos(){counter.textContent=`${existing.length+added.length} / 3`;preview.innerHTML=[...existing.map((url,i)=>`<div class="preview-item"><img src="${escapeHTML(url)}" alt="Existing photo ${i+1}"><button type="button" data-existing="${i}" aria-label="Remove photo">×</button></div>`),...added.map((f,i)=>`<div class="preview-item"><img src="${URL.createObjectURL(f)}" alt="New photo ${i+1}"><button type="button" data-added="${i}" aria-label="Remove photo">×</button></div>`)].join("")}
async function load(){await requireAuth();if(!id){toast("Missing listing id.","error");return}const {data:user}=await supabase.auth.getUser();let q=supabase.from(table).select("*").eq("id",id).maybeSingle();const {data,error}=await q;if(error||!data){toast("Listing could not be loaded.","error");return}if(data[ownerField]!==user.user?.id){toast("You can only edit your own listings.","error");setTimeout(()=>location.href=back,700);return}record=data;existing=Array.isArray(data.image_urls)&&data.image_urls.length?data.image_urls.slice():data.image_url?[data.image_url]:[];fields.innerHTML=build(data);document.querySelector("#editTitle").textContent=`Edit ${label.toLowerCase()}`;document.querySelector("#editDescription").textContent=`Update your ${label.toLowerCase()} and keep the information current.`;document.querySelector("#editBack").href=`marketplace-detail.html?type=${type}&id=${encodeURIComponent(id)}`;renderPhotos()}
document.querySelector("#editImages")?.addEventListener("change",e=>{const incoming=Array.from(e.target.files||[]);const room=Math.max(0,3-existing.length);added=incoming.slice(0,room);if(incoming.length>room)toast(`Only ${room} more photo${room===1?"":"s"} can be added.`,"warning");renderPhotos()});
preview?.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.existing!==undefined)existing.splice(Number(b.dataset.existing),1);if(b.dataset.added!==undefined)added.splice(Number(b.dataset.added),1);renderPhotos()});
form?.addEventListener("submit",async e=>{e.preventDefault();try{loading(button,true,"Saving...");const fd=new FormData(form);const newUrls=await uploadPublicMany(added,`${type}-edit`,3-existing.length);const image_urls=[...existing,...newUrls].slice(0,3);let payload={image_urls,updated_at:new Date().toISOString()};if(type==="marketplace")Object.assign(payload,{title:String(fd.get("title")).trim(),category:String(fd.get("category")).trim(),price:Number(fd.get("price"))||null,contact_number:String(fd.get("contact_number")).trim(),item_condition:String(fd.get("item_condition")).trim(),location_details:String(fd.get("location_details")).trim()||null,description:String(fd.get("description")).trim()||null});
if(type==="housing")Object.assign(payload,{title:String(fd.get("title")).trim(),location_details:String(fd.get("location_details")).trim(),rent:Number(fd.get("rent"))||null,contact_number:String(fd.get("contact_number")).trim(),utilities:String(fd.get("utilities")).trim()||null,security_notes:String(fd.get("security_notes")).trim()||null,description:String(fd.get("description")).trim()||null});
if(type==="printing")Object.assign(payload,{name:String(fd.get("name")).trim(),location_details:String(fd.get("location_details")).trim()||null,contact_number:String(fd.get("contact_number")).trim(),available:fd.get("available")==="true",notes:String(fd.get("notes")).trim()||null});
if(type==="academic"){Object.assign(payload,{title:String(fd.get("title")).trim(),department:String(fd.get("department")).trim(),academic_year:String(fd.get("academic_year")).trim()||null,course_code:String(fd.get("course_code")).trim()||null});const file=fd.get("resourceFile");if(file?.size){const path=`${record[ownerField]}/academic/${crypto.randomUUID()}-${file.name.replace(/[^\w.\-]/g,"_")}`;const {error}=await supabase.storage.from("hub-private").upload(path,file,{upsert:false});if(error)throw error;payload.file_url=path;payload.file_name=file.name}}
if(type==="service")Object.assign(payload,{provider_name:String(fd.get("provider_name")).trim(),service_title:String(fd.get("service_title")).trim(),skill_category:String(fd.get("skill_category")).trim(),contact_number:String(fd.get("contact_number")).trim(),starting_price:Number(fd.get("starting_price"))||0,description:String(fd.get("description")).trim()||null});
const {error}=await supabase.from(table).update(payload).eq("id",id);if(error)throw error;const removed=record.image_urls?.filter(x=>!image_urls.includes(x))||[];const paths=removed.map(publicUrlToPath).filter(Boolean);if(paths.length)await deletePublicFiles(paths).catch(()=>{});toast("Listing updated successfully.","success");setTimeout(()=>location.href=`marketplace-detail.html?type=${type}&id=${encodeURIComponent(id)}`,600)}catch(err){console.error(err);toast(err.message||"Could not save changes.","error")}finally{loading(button,false)}});
load();
