-- Domasi Hub Supabase BaaS schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text not null,
 reg_number text not null unique,
 whatsapp_number text,
 avatar_url text,
 created_at timestamptz not null default now()
);

create table if not exists public.listings (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade not null default auth.uid(),
 posted_by text,
 title text not null,
 category text not null check (category in ('marketplace','printing','accommodation')),
 price numeric not null default 0,
 contact_number text not null,
 item_condition text,
 security_condition text,
 location_details text,
 image_path text,
 created_at timestamptz not null default now()
);

create table if not exists public.academic_resources (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade not null default auth.uid(),
 title text not null,
 department text not null,
 academic_year text,
 course_code text,
 file_data text not null,
 uploaded_by text,
 download_count integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists public.skill_services (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade default auth.uid(),
 provider_name text not null,
 skill_category text not null,
 service_title text not null,
 description text,
 starting_price numeric default 0,
 contact_number text not null,
 portfolio_link text,
 created_at timestamptz not null default now()
);

create table if not exists public.campus_landmarks (
 id bigint generated by default as identity primary key,
 name text not null, type text not null, description text,
 latitude real not null, longitude real not null, contact_number text
);

create table if not exists public.bulletins (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade default auth.uid(),
 notice_type text not null, title text not null, description text not null,
 posted_by text, event_date text, created_at timestamptz not null default now()
);

create or replace function public.increment_download(resource_id bigint)
returns void language sql security definer set search_path=public
as $$ update public.academic_resources set download_count=download_count+1 where id=resource_id; $$;

alter table public.profiles enable row level security;
alter table public.listings enable row level security;
alter table public.academic_resources enable row level security;
alter table public.skill_services enable row level security;
alter table public.campus_landmarks enable row level security;
alter table public.bulletins enable row level security;

create policy "profiles readable by authenticated users" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());
create policy "users insert own profile" on public.profiles for insert to authenticated with check (id=auth.uid());

create policy "public read listings" on public.listings for select using (true);
create policy "users create listings" on public.listings for insert to authenticated with check (user_id=auth.uid());
create policy "users update own listings" on public.listings for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "users delete own listings" on public.listings for delete to authenticated using (user_id=auth.uid());

create policy "public read academic resources" on public.academic_resources for select using (true);
create policy "users upload resources" on public.academic_resources for insert to authenticated with check (user_id=auth.uid());
create policy "users update own resources" on public.academic_resources for update to authenticated using (user_id=auth.uid());

create policy "public read skills" on public.skill_services for select using (true);
create policy "users manage own skills" on public.skill_services for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "public read landmarks" on public.campus_landmarks for select using (true);
create policy "public read bulletins" on public.bulletins for select using (true);
create policy "users create bulletins" on public.bulletins for insert to authenticated with check (user_id=auth.uid());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('domasi-hub','domasi-hub',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do nothing;

create policy "public read bucket" on storage.objects for select using (bucket_id='domasi-hub');
create policy "authenticated upload bucket" on storage.objects for insert to authenticated with check (bucket_id='domasi-hub' and owner=auth.uid());
create policy "owners update bucket files" on storage.objects for update to authenticated using (bucket_id='domasi-hub' and owner=auth.uid());
create policy "owners delete bucket files" on storage.objects for delete to authenticated using (bucket_id='domasi-hub' and owner=auth.uid());
